name: 자바 배포 테스트

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: java 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 소스코드 체크 아웃
        uses: actions/checkout@v4

      - name: 소스코드 빌드
        run: |
          chmod +x gradlew